### ISSUE TITLE
Issue with Probing Phase Example Execution for e1000 in DevFuzz

### ISSUE THREAD

**Issue by C0D1NGK1NG** [yiluwusbu/DEVFUZZ#2]
When attempting to perform probing phase fuzzing using the example provided in the README (`e1000`), I encountered the following output (refer to the attached screenshot).
![2024-12-25 18-57-33屏幕截图](https://github.com/user-attachments/assets/8e0a0997-7e8c-4836-ad1f-d1fd751310e8)
1. Is the output displayed in the probing stage correct and expected for the`e1000`example?
2. Should I modify the NIC field in the QEMU startup script to change `-net none` to something related to `e1000`, or is this unnecessary?
3. In some tests, AFL starts, and QEMU also starts the virtual machine, but it seems that there is no communication between the two.

**Comment by yiluwusbu** [comment]
1. I don't see a significant problem in your screenshot.  
2. It is better to use -net none because otherwise QEMU's emulated device will be used and potentially interfare with the system (and the fuzzing effectiveness). We use -net none for network drivers fuzzing in our paper.
3. QEMU/Linux VM and AFL communicates  via shared memory. DEVFuzz updates the AFL's bitmap (hit counts) using intel PT. You can find most of the code implementing the communication under this directory: https://github.com/yiluwusbu/DEVFUZZ/tree/master/afl-proxy/proxy
